/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

/**
 *
 * @author Shajal
 */
public class Convert extends javax.swing.JFrame {

    /**
     * Creates new form Convert
     */
    public Convert() {
        initComponents();
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText(" Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jTextField1.setText("Enter value");

        jTextField2.setText("Result");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(jTextField2))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("To");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click", "Temparature", "Lenght", "Currency", " " }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Choice");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 0, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 51, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, 127, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String current;
        current=jComboBox3.getSelectedItem().toString();
     
        switch(current){
            
        case "Temparature": 
            
        double n;
        String to;
        String from;
        Double result;
        n = Double.parseDouble(jTextField1.getText()) ;
        to  = jComboBox2.getSelectedItem().toString();
        from  = jComboBox1.getSelectedItem().toString();
         
          if ( from.equals("Celsius") ){
           switch(to){
               case "Fahrenheit" :
                    result = ((9.0 / 5.0 ) * n) + 32;
                    jTextField2.setText(result.toString());
                   break ;
               case "Kelvin" :
                    result = (n*1)+273.15;
                    jTextField2.setText(result.toString());
                    break ;
               default  :
                    result = n *1;
                    jTextField2.setText(result.toString());                 
          }
       }
           if ( from.equals("Fahrenheit") ){
           switch(to){
               case "Celsius" :
                    result = (n-32)*5/9;
                    jTextField2.setText(result.toString());
                   break ;
               case "Kelvin" :
                    result = ((n-32)*5/9)+273.15;
                    jTextField2.setText(result.toString());
                    break ;
               default  :
                    result = n *1;
                    jTextField2.setText(result.toString());                 
          }
       }
           if ( from.equals("Kelvin") ){
           switch(to){
               case "Fahrenheit" :
                    result = ((n-273.15)*9/5)+32;
                    jTextField2.setText(result.toString());
                   break ;
               case "Celsius" :
                    result = n-273.15;
                    jTextField2.setText(result.toString());
                    break ;
               default  :
                    result = n *1;
                    jTextField2.setText(result.toString());                 
          }
           }   
           
       case "Lenght":
              
        double nn;
        String too;
        String fromm;
        Double resultt;
        nn = Double.parseDouble(jTextField1.getText()) ;
        too  = jComboBox2.getSelectedItem().toString();
        fromm  = jComboBox1.getSelectedItem().toString();
         
          if ( fromm.equals("Kilometer") ){
           switch(too){
               case "Meter" :
                    resultt =nn*1000;
                    jTextField2.setText(resultt.toString());
                   break;
               
                    case "Inches" :
                    resultt = nn*39370.08;
                    jTextField2.setText(resultt.toString());
                    break ;
                    case "Centimeter" :
                    resultt = nn*100000;
                    jTextField2.setText(resultt.toString());
                    break; 
               default  :
                    resultt = nn *1;
                    jTextField2.setText(resultt.toString());                 
          }
       }
           if ( fromm.equals("Meter") ){
           switch(too){
               case "Kilometer" :
                    resultt = nn/1000;
                    jTextField2.setText(resultt.toString());
                   break ;
               case "Inches" :
                    resultt = nn*39.3701;
                    jTextField2.setText(resultt.toString());
                    break ;
                    case "Centimeter" :
                    resultt = nn*100;
                    jTextField2.setText(resultt.toString());
                    break ;
               default  :
                    resultt = nn *1;
                    jTextField2.setText(resultt.toString());                 
          }
       }
              if ( fromm.equals("Inches") ){
           switch(too){
               case "Kilometer" :
                    resultt = nn*0.0000254;
                    jTextField2.setText(resultt.toString());
                   break ;
               case "Meter" :
                    resultt = nn*0.0254;
                    jTextField2.setText(resultt.toString());
                    break ;
                    case "Centimeter" :
                    resultt = nn*2.54;
                    jTextField2.setText(resultt.toString());
                    break ;
               default  :
                    resultt = nn *1;
                    jTextField2.setText(resultt.toString());        
          }
           }   
               if ( fromm.equals("Centimeter") ){
           switch(too){
               case "Kilometer" :
                    resultt = nn*0.00001;
                    jTextField2.setText(resultt.toString());
                   break ;
               case "Meter" :
                    resultt = nn*0.01;
                    jTextField2.setText(resultt.toString());
                    break ;
                    case "Inches" :
                    resultt = nn*0.393701;
                    jTextField2.setText(resultt.toString());
                    break ;
               default  :
                    resultt = nn *1;
                    jTextField2.setText(resultt.toString());
               
    }//GEN-LAST:event_jButton1ActionPerformed
    
           }
      case "Currency":
                   
        double nnn;
        String tooo;
        String frommm;
        Double resulttt;
        nnn = Double.parseDouble(jTextField1.getText()) ;
        tooo  = jComboBox2.getSelectedItem().toString();
        frommm  = jComboBox1.getSelectedItem().toString();
                   
              if ( frommm.equals("US Doller") ){
           switch(tooo){
               case "Euro" :
                    resulttt =nnn*0.89;
                    jTextField2.setText(resulttt.toString());
                   break;
               
                    case "Saudia Riyal" :
                    resulttt = nnn*3.75;
                    jTextField2.setText(resulttt.toString());
                    break ;
                    case "Taka" :
                    resulttt = nnn*78.32;
                    jTextField2.setText(resulttt.toString());
                    break; 
               default  :
                    resulttt = nnn*1;
                    jTextField2.setText(resulttt.toString());                 
          }
       }     
            
               if ( frommm.equals("Euro") ){
           switch(tooo){
               case "US Doller" :
                    resulttt =nnn*1.12;
                    jTextField2.setText(resulttt.toString());
                   break;
               
                    case "Saudia Riyal" :
                    resulttt = nnn*4.21;
                    jTextField2.setText(resulttt.toString());
                    break ;
                    case "Taka" :
                    resulttt = nnn*87.91;
                    jTextField2.setText(resulttt.toString());
                    break; 
               default  :
                    resulttt = nnn*1;
                    jTextField2.setText(resulttt.toString());
              
        }
        
               }
                if ( frommm.equals("Saudia Riyal") ){
           switch(tooo){
               case "Euro" :
                    resulttt =nnn*0.24;
                    jTextField2.setText(resulttt.toString());
                   break;
               
                    case "US Doller" :
                    resulttt = nnn*0.27;
                    jTextField2.setText(resulttt.toString());
                    break ;
                    case "Taka" :
                    resulttt = nnn*20.88;
                    jTextField2.setText(resulttt.toString());
                    break; 
               default  :
                    resulttt = nnn*1;
                    jTextField2.setText(resulttt.toString());   
    }
    }
                
                 if ( frommm.equals("Taka") ){
           switch(tooo){
               case "Euro" :
                    resulttt =nnn*0.011;
                    jTextField2.setText(resulttt.toString());
                   break;
               
                    case "Saudia Riyal" :
                    resulttt = nnn*0.048;
                    jTextField2.setText(resulttt.toString());
                    break ;
                    case "US Doller" :
                    resulttt = nnn*0.013;
                    jTextField2.setText(resulttt.toString());
                    break; 
               default  :
                    resulttt = nnn*1;
                    jTextField2.setText(resulttt.toString());
           }
                 }
        }
    }           
                
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       jTextField1.setText("Enter Value");
       jTextField2.setText("Result");
       jComboBox1.removeAllItems();
       jComboBox2.removeAllItems();
       jComboBox3.setSelectedIndex(0);
       
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
          String currentt;
        currentt=jComboBox3.getSelectedItem().toString();
        
        switch(currentt){
            case "Temparature":
                jComboBox1.addItem("Celsius");
                jComboBox1.addItem("Fahrenheit");
                jComboBox1.addItem("Kelvin");
                jComboBox2.addItem("Celsius");
                jComboBox2.addItem("Fahrenheit");
                jComboBox2.addItem("Kelvin");
                break;
            case "Lenght":
                jComboBox1.addItem("Kilometer");
                jComboBox1.addItem("Meter");
                jComboBox1.addItem("Inches");
                jComboBox1.addItem("Centimeter");
                jComboBox2.addItem("Kilometer");
                jComboBox2.addItem("Meter");
                jComboBox2.addItem("Inches");
                jComboBox2.addItem("Centimeter");
                break;
              case "Currency":
                jComboBox1.addItem("US Doller");
                jComboBox1.addItem("Euro");
                jComboBox1.addItem("Saudia Riyal");
                jComboBox1.addItem("Taka");
                jComboBox2.addItem("US Doller");
                jComboBox2.addItem("Euro");
                jComboBox2.addItem("Saudia Riyal");
                jComboBox2.addItem("Taka");
                break;
        }    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
